import type { GenerateTestResult } from "./types.js";

export function buildBranchName(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const timestamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
  return `anqa/generate-${timestamp}`;
}

interface PRBodyOptions {
  tests: GenerateTestResult[];
  targetUrl: string;
  coverageBefore: number;
  coverageAfter: number;
  estimatedCost: number;
  failedCount: number;
}

export function buildPRBody(options: PRBodyOptions): string {
  const { tests, targetUrl, coverageBefore, coverageAfter, estimatedCost, failedCount } = options;

  const flowRows = tests
    .filter((t) => t.status === "passing")
    .map((t) => `| ${t.flow_name} | ${t.priority} | passing | ${t.heal_attempts} |`)
    .join("\n");

  let body = `## Agentic Ninja QA — Generated Tests

Automated Playwright tests for uncovered flows identified by coverage audit.

### Flows Covered

| Flow | Priority | Status | Heal Attempts |
|------|----------|--------|---------------|
${flowRows}

### Summary
- **Tests generated:** ${tests.filter((t) => t.status === "passing").length}
- **All passing** against \`${targetUrl}\`
- **Coverage improvement:** ${coverageBefore}% → ${coverageAfter}% (estimated)
- **Estimated token cost:** ~$${estimatedCost.toFixed(2)}

### How to run
\`\`\`bash
npx playwright test tests/anqa/
\`\`\`

> **Note:** If your \`playwright.config.ts\` sets a custom \`testDir\`, you may need to
> add \`tests/anqa/\` to your config or move these files to your test directory.

### What's next
Merge this PR to add test coverage. Future audit runs will detect these tests
and update your coverage score.

---
Generated by [Agentic Ninja QA](https://anqa.dev)`;

  if (failedCount > 0) {
    body += `\n\n> ${failedCount} additional flows attempted but excluded due to test failures. See run details on your dashboard.`;
  }

  return body;
}
